### ISSUE TITLE
Gather best/good practices

### ISSUE THREAD

**Issue by ericmartinezr** [escardin/angular2-community-faq#18]
We know about a few ones
- Don't use EventEmitters in services. More generically don't subscribe to them. I have an [answer](http://stackoverflow.com/questions/36076700/what-is-the-proper-use-of-an-eventemitter) in SO explaining it.
- Don't handle the DOM directly using `nativeElement`, instead use `Renderer`. Although it's specified in the docs there are no really good examples of its usage. I have another [answer](http://stackoverflow.com/questions/36108995/what-are-some-good-alternatives-to-accessing-the-dom-using-nativeelement-in-angu) in SO for this subject.
- Don't use Subject (or avoid them as much as possible)

What do you think?

**Comment by escardin** [comment]
I think it's a great idea! I would also add some better examples of ngcontent and view/content child/children, and maybe the DCL.

**Comment by escardin** [comment]
Should add testing examples/resources as well

**Comment by ericmartinezr** [comment]
@escardin I created a new issue about testing examples, I don't think they should go with best/good practices

**Comment by escardin** [comment]
Sound good.

**Comment by escardin** [comment]
I think when to use and when not to use pipes is also a good subject for best practices

**Comment by ericmartinezr** [comment]
@escardin what do you mean exactly? Do you mean in case I'm subscribing manually  to some http call I should not use `async`, right?

**Comment by escardin** [comment]
I mean you shouldn't filter or sort data in pipes, you should do it before it gets to the view. From what I've seen, other than the async pipe, all pipes just transform data for display (like the json or date pipe)

**Comment by ericmartinezr** [comment]
@escardin got it :+1:

**Comment by ericmartinezr** [comment]
Thought of two more
- Don't mix angular2 with other libs (specially jQuery), or do it carefully.
- Don't do any type of calculations  (specially DOM)  in ngAfterViewChecked/ngAfterContentChecked

I'll keep adding them when I think of more.

**Comment by ericmartinezr** [comment]
Using `@Injectable()` in every service (see https://github.com/angular/angular.io/pull/1012#issuecomment-202326319). Explain that it's only for TypeScript to emit metadata, point to Pascal's article.

**Comment by ericmartinezr** [comment]
Let's continue in the other issue.
