### ISSUE TITLE
Explanation of placing services in providers/bootstrap

### ISSUE THREAD

**Issue by brandonroberts** [escardin/angular2-community-faq#34]
I think we keep seeing people put services into component's `providers` array and getting a new instance  each time when they really want one instance for the application.

**Comment by ericmartinezr** [comment]
I think this should be covered by 

https://angular.io/docs/ts/latest/guide/dependency-injection.html
https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html

Haven't ready any of them, but I'll leave them for later.

**Comment by CaptainCodeman** [comment]
one useful thing that isn't documented AFAIK is deferred / lazy service setup. I use this where there is some remote app runtime config needed but you don't want to have to wait for it to be loaded to start initializing the app. Not intuitive though.
